namespace ParserWebCore.BuilderApp
{
    public enum Arguments
    {
        Agrocomplex,
        Kzgroup,
        Agrotomsk,
        Sibintek,
        Setonline,
        Mzvoron,
        Maxi,
        Tver,
        Murman,
        Kalug,
        Smol,
        Samar,
        Udmurt,
        Segezha,
        Akashevo,
        Sitno,
        Naftan,
        Rwby,
        Tekkom,
        Tekmarket,
        Tekmos,
        Mlconf,
        Tekrn,
        Brn32,
        SportMaster,
        Teksil
    }
}